/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    events: Event;
    'menu-categories': MenuCategory;
    'gallery-videos': GalleryVideo;
    'gallery-reports': GalleryReport;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'menu-categories': MenuCategoriesSelect<false> | MenuCategoriesSelect<true>;
    'gallery-videos': GalleryVideosSelect<false> | GalleryVideosSelect<true>;
    'gallery-reports': GalleryReportsSelect<false> | GalleryReportsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    settings: Setting;
    'home-content': HomeContent;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
    'home-content': HomeContentSelect<false> | HomeContentSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  subtitle?: string | null;
  slug: string;
  description: string;
  category: 'all' | 'karaoke' | 'quiz' | 'music' | 'business' | 'show';
  date: string;
  month: string;
  dayOfWeek: 'Понедельник' | 'Вторник' | 'Среда' | 'Четверг' | 'Пятница' | 'Суббота' | 'Воскресенье';
  time: string;
  scheduleType: 'recurring' | 'one-off';
  specificDate?: string | null;
  image: number | Media;
  admission: 'free' | 'paid';
  heroLines?:
    | {
        line?: string | null;
        id?: string | null;
      }[]
    | null;
  heroSubtitle?: string | null;
  programHeading?: string | null;
  features?:
    | {
        icon?: string | null;
        title?: string | null;
        desc?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Все изображения сайта. Загружайте сюда картинки для событий, меню и галереи.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Текст для доступности и SEO. Опишите, что изображено на картинке. Например: "Караоке-батл в ресторане, ночная вечеринка"
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-categories".
 */
export interface MenuCategory {
  id: number;
  slug: string;
  title: string;
  subtitle: string;
  image: number | Media;
  group: 'main' | 'alcohol' | 'non-alcohol';
  order?: number | null;
  sections?:
    | {
        /**
         * Если в категории только одна секция — заголовок и подзаголовок на сайте не отображаются.
         */
        title: string;
        /**
         * Если в категории только одна секция — заголовок и подзаголовок на сайте не отображаются.
         */
        subtitle?: string | null;
        dishes?:
          | {
              name: string;
              description?: string | null;
              subtitle?: string | null;
              base?: string | null;
              composition?: string | null;
              weight?: string | null;
              price: string;
              discount?: number | null;
              /**
               * Выберите бейдж(и) из списка возможных вариантов.
               */
              badges?:
                | {
                    text: 'Премиум' | 'Веганское блюдо' | 'Вегетарианское блюдо' | 'Без добавленного сахара';
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-videos".
 */
export interface GalleryVideo {
  id: number;
  /**
   * Например: «Караоке батл», «DJ вечеринка». Можно оставить пустым, если в группе есть названия роликов.
   */
  title: string;
  /**
   * Добавьте ссылки YouTube на все ролики этого дня. ID подставится автоматически.
   */
  videos: {
    /**
     * Необязательно — подставится название отчёта.
     */
    title?: string | null;
    videoUrl: string;
    videoId: string;
    id?: string | null;
  }[];
  videoId?: string | null;
  reportDate?: string | null;
  dateKey: string;
  dateLabel: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-reports".
 */
export interface GalleryReport {
  id: number;
  title: string;
  slug: string;
  description: string;
  category: 'all' | 'karaoke' | 'quiz' | 'music' | 'business' | 'show';
  reportDate?: string | null;
  date: string;
  month: string;
  dayOfWeek: string;
  time: string;
  /**
   * Используется на главной странице. Остальные фото добавляйте ниже.
   */
  image: number | Media;
  /**
   * Добавьте все фото мероприятия этого дня. Первое фото используется как обложка, если главное фото не задано.
   */
  photos?:
    | {
        /**
         * Необязательно — подставится название отчёта.
         */
        title?: string | null;
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  admission: 'free' | 'paid';
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'menu-categories';
        value: number | MenuCategory;
      } | null)
    | ({
        relationTo: 'gallery-videos';
        value: number | GalleryVideo;
      } | null)
    | ({
        relationTo: 'gallery-reports';
        value: number | GalleryReport;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  slug?: T;
  description?: T;
  category?: T;
  date?: T;
  month?: T;
  dayOfWeek?: T;
  time?: T;
  scheduleType?: T;
  specificDate?: T;
  image?: T;
  admission?: T;
  heroLines?:
    | T
    | {
        line?: T;
        id?: T;
      };
  heroSubtitle?: T;
  programHeading?: T;
  features?:
    | T
    | {
        icon?: T;
        title?: T;
        desc?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-categories_select".
 */
export interface MenuCategoriesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  subtitle?: T;
  image?: T;
  group?: T;
  order?: T;
  sections?:
    | T
    | {
        title?: T;
        subtitle?: T;
        dishes?:
          | T
          | {
              name?: T;
              description?: T;
              subtitle?: T;
              base?: T;
              composition?: T;
              weight?: T;
              price?: T;
              discount?: T;
              badges?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-videos_select".
 */
export interface GalleryVideosSelect<T extends boolean = true> {
  title?: T;
  videos?:
    | T
    | {
        title?: T;
        videoUrl?: T;
        videoId?: T;
        id?: T;
      };
  videoId?: T;
  reportDate?: T;
  dateKey?: T;
  dateLabel?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-reports_select".
 */
export interface GalleryReportsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  category?: T;
  reportDate?: T;
  date?: T;
  month?: T;
  dayOfWeek?: T;
  time?: T;
  image?: T;
  photos?:
    | T
    | {
        title?: T;
        image?: T;
        id?: T;
      };
  admission?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  siteName?: string | null;
  tagline?: string | null;
  description?: string | null;
  footerHeart?: string | null;
  cuisines?: string | null;
  neonSlogan?: {
    line1?: string | null;
    accent1?: string | null;
    accent2?: string | null;
    subtitle?: string | null;
  };
  phone?: string | null;
  phoneHref?: string | null;
  email?: string | null;
  address?: string | null;
  addressFull?: string | null;
  telegram?: string | null;
  telegramBot?: string | null;
  whatsapp?: string | null;
  instagram?: string | null;
  facebook?: string | null;
  youtube?: string | null;
  tiktok?: string | null;
  zalo?: string | null;
  googleMaps?: string | null;
  yandexMaps?: string | null;
  grab?: string | null;
  workingHours?: {
    label?: string | null;
    hours?: string | null;
    highlighted?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-content".
 */
export interface HomeContent {
  id: number;
  title?: {
    text?: string | null;
    accent?: string | null;
  };
  /**
   * Кухни разделяются значком •
   */
  cuisines?: string | null;
  neonSlogan?: {
    line1?: string | null;
    accent1?: string | null;
    accent2?: string | null;
    subtitle?: string | null;
  };
  services?:
    | {
        icon?: string | null;
        title: string;
        description: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Строго 4 пункта: текст, ссылка и иконка.
   */
  quickNav?:
    | {
        icon: string;
        label: string;
        desc: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Выберите фотоотчёты из списка. Если ничего не выбрано — покажутся все.
   */
  galleryPhotos?: (number | GalleryReport)[] | null;
  /**
   * Выберите видеоотчёты из списка. Если ничего не выбрано — покажутся все.
   */
  galleryVideos?: (number | GalleryVideo)[] | null;
  menuTitle?: string | null;
  eventsTitle?: string | null;
  galleryTitle?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  description?: T;
  footerHeart?: T;
  cuisines?: T;
  neonSlogan?:
    | T
    | {
        line1?: T;
        accent1?: T;
        accent2?: T;
        subtitle?: T;
      };
  phone?: T;
  phoneHref?: T;
  email?: T;
  address?: T;
  addressFull?: T;
  telegram?: T;
  telegramBot?: T;
  whatsapp?: T;
  instagram?: T;
  facebook?: T;
  youtube?: T;
  tiktok?: T;
  zalo?: T;
  googleMaps?: T;
  yandexMaps?: T;
  grab?: T;
  workingHours?:
    | T
    | {
        label?: T;
        hours?: T;
        highlighted?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-content_select".
 */
export interface HomeContentSelect<T extends boolean = true> {
  title?:
    | T
    | {
        text?: T;
        accent?: T;
      };
  cuisines?: T;
  neonSlogan?:
    | T
    | {
        line1?: T;
        accent1?: T;
        accent2?: T;
        subtitle?: T;
      };
  services?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        href?: T;
        id?: T;
      };
  quickNav?:
    | T
    | {
        icon?: T;
        label?: T;
        desc?: T;
        href?: T;
        id?: T;
      };
  galleryPhotos?: T;
  galleryVideos?: T;
  menuTitle?: T;
  eventsTitle?: T;
  galleryTitle?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}