import type { EventItem } from "@/types"

export const events: EventItem[] = [
  {
    id: "karaoke-battle-1",
    date: "24",
    month: "МАЯ",
    dayOfWeek: "Пятница",
    title: "Караоке батл",
    category: "karaoke",
    time: "20:00",
    image: "https://picsum.photos/seed/poidem-karaoke/400/500",
    description: "Пой и побеждай! Лучший голос вечера получает приз.",
    admission: "free",
    slug: "karaoke-battle-1",
  },
  {
    id: "quiz-1",
    date: "25",
    month: "МАЯ",
    dayOfWeek: "Суббота",
    title: "Квиз «Пойдём пожрём!»",
    category: "quiz",
    time: "21:00",
    image: "https://picsum.photos/seed/poidem-quiz/400/500",
    description: "Интеллектуальная битва с вкусными призами.",
    admission: "free",
    slug: "quiz-1",
  },
  {
    id: "dj-party-1",
    date: "26",
    month: "МАЯ",
    dayOfWeek: "Воскресенье",
    title: "DJ вечеринка",
    category: "music",
    time: "21:00",
    image: "https://picsum.photos/seed/poidem-dj/400/500",
    description: "Танцы всю ночь с лучшими диджеями острова.",
    admission: "free",
    slug: "dj-party-1",
  },
  {
    id: "business-breakfast-1",
    date: "28",
    month: "МАЯ",
    dayOfWeek: "Вторник",
    title: "Бизнес-завтрак",
    category: "business",
    time: "09:00",
    image: "https://picsum.photos/seed/poidem-business/400/500",
    description: "Нетворкинг и полезные знакомства за завтраком.",
    admission: "paid",
    slug: "business-breakfast-1",
  },
  {
    id: "live-music-1",
    date: "30",
    month: "МАЯ",
    dayOfWeek: "Четверг",
    title: "Живая музыка",
    subtitle: "Акустический вечер",
    category: "music",
    time: "20:00",
    image: "https://picsum.photos/seed/poidem-live-music/400/500",
    description: "Акустический вечер с живым вокалом.",
    admission: "free",
    slug: "live-music-1",
  },
  {
    id: "karaoke-battle-2",
    date: "01",
    month: "ИЮНЯ",
    dayOfWeek: "Воскресенье",
    title: "Караоке батл",
    category: "karaoke",
    time: "20:00",
    image: "https://picsum.photos/seed/poidem-karaoke-2/400/500",
    description: "Еженедельный караоке-батл с новыми призами.",
    admission: "free",
    slug: "karaoke-battle-2",
  },
  {
    id: "show-program-1",
    date: "05",
    month: "ИЮНЯ",
    dayOfWeek: "Четверг",
    title: "Шоу-программа «Кавказская ночь»",
    category: "show",
    time: "21:00",
    image: "https://picsum.photos/seed/poidem-show/400/500",
    description: "Яркое шоу с элементами кавказской культуры и танцами.",
    admission: "free",
    slug: "show-program-1",
  },
  {
    id: "business-breakfast-2",
    date: "11",
    month: "ИЮНЯ",
    dayOfWeek: "Среда",
    title: "Бизнес-завтрак",
    category: "business",
    time: "09:00",
    image: "https://picsum.photos/seed/poidem-business-2/400/500",
    description: "Встреча предпринимателей и нетворкинг.",
    admission: "paid",
    slug: "business-breakfast-2",
  },
  {
    id: "dj-party-2",
    date: "14",
    month: "ИЮНЯ",
    dayOfWeek: "Суббота",
    title: "DJ вечеринка «Weekend Vibes»",
    category: "music",
    time: "22:00",
    image: "https://picsum.photos/seed/poidem-dj-2/400/500",
    description: "Лучшие треки и танцы до утра.",
    admission: "free",
    slug: "dj-party-2",
  },
  {
    id: "quiz-2",
    date: "21",
    month: "ИЮНЯ",
    dayOfWeek: "Суббота",
    title: "Квиз «Пойдём пожрём!»",
    category: "quiz",
    time: "21:00",
    image: "https://picsum.photos/seed/poidem-quiz-2/400/500",
    description: "Новые вопросы, новые призы, новые эмоции.",
    admission: "free",
    slug: "quiz-2",
  },
]
