import type { EventItem } from "@/types"

export const events: EventItem[] = [
  {
    id: "after-weekend-party",
    date: "03",
    month: "АВГУСТА",
    dayOfWeek: "Понедельник",
    title: "After Weekend Party",
    category: "music",
    time: "21:00",
    image: "https://picsum.photos/seed/poidem-monday/400/500",
    description: "После насыщенных выходных — время для отличной вечеринки. Танцы, музыка и хорошее настроение.",
    admission: "free",
    slug: "after-weekend-party",
  },
  {
    id: "business-breakfast",
    date: "04",
    month: "АВГУСТА",
    dayOfWeek: "Вторник",
    title: "Бизнес-завтрак",
    category: "business",
    time: "09:00",
    image: "https://picsum.photos/seed/poidem-business/400/500",
    description: "Нетворкинг и полезные знакомства за завтраком. Обсуждение бизнес-идей в уютной атмосфере.",
    admission: "paid",
    slug: "business-breakfast",
  },
  {
    id: "quiz-poidem-pozhrem",
    date: "05",
    month: "АВГУСТА",
    dayOfWeek: "Среда",
    title: "Квиз «Пойдём пожрём!»",
    category: "quiz",
    time: "21:00",
    image: "https://picsum.photos/seed/poidem-quiz/400/500",
    description: "Интеллектуальная битва с вкусными призами. Собери команду и покажи эрудицию!",
    admission: "free",
    slug: "quiz-poidem-pozhrem",
  },
  {
    id: "live-music",
    date: "06",
    month: "АВГУСТА",
    dayOfWeek: "Четверг",
    title: "Живая музыка",
    subtitle: "Акустический вечер",
    category: "music",
    time: "20:00",
    image: "https://picsum.photos/seed/poidem-live-music/400/500",
    description: "Акустический вечер с живым вокалом и инструментальным исполнением любимых хитов.",
    admission: "free",
    slug: "live-music",
  },
  {
    id: "karaoke-battle",
    date: "07",
    month: "АВГУСТА",
    dayOfWeek: "Пятница",
    title: "Караоке батл",
    category: "karaoke",
    time: "20:00",
    image: "https://picsum.photos/seed/poidem-karaoke/400/500",
    description: "Пой и побеждай! Лучший голос вечера получает приз. Караоке-батл каждую пятницу.",
    admission: "free",
    slug: "karaoke-battle",
  },
  {
    id: "dj-party",
    date: "08",
    month: "АВГУСТА",
    dayOfWeek: "Суббота",
    title: "DJ вечеринка",
    category: "music",
    time: "22:00",
    image: "https://picsum.photos/seed/poidem-dj/400/500",
    description: "Танцы всю ночь с лучшими диджеями. Зажигательные треки и отличное настроение.",
    admission: "free",
    slug: "dj-party",
  },
  {
    id: "show-program",
    date: "09",
    month: "АВГУСТА",
    dayOfWeek: "Воскресенье",
    title: "Шоу-программа",
    category: "show",
    time: "21:00",
    image: "https://picsum.photos/seed/poidem-show/400/500",
    description: "Яркое шоу с зажигательными номерами, танцами и незабываемой атмосферой.",
    admission: "free",
    slug: "show-program",
  },
]
