import type { GalleryPhoto } from "@/types"

export const galleryPhotos: GalleryPhoto[] = [
  { id: "p1", image: "https://picsum.photos/seed/poidem-photo-1/400/400", title: "Караоке батл", dateKey: "2026-05-24", dateLabel: "24 мая" },
  { id: "p2", image: "https://picsum.photos/seed/poidem-photo-2/400/400", title: "DJ вечеринка", dateKey: "2026-05-24", dateLabel: "24 мая" },
  { id: "p3", image: "https://picsum.photos/seed/poidem-photo-3/400/400", title: "Квиз", dateKey: "2026-05-24", dateLabel: "24 мая" },
  { id: "p4", image: "https://picsum.photos/seed/poidem-photo-4/400/400", title: "Бизнес-завтрак", dateKey: "2026-05-24", dateLabel: "24 мая" },
  { id: "p5", image: "https://picsum.photos/seed/poidem-photo-5/400/400", title: "Живая музыка", dateKey: "2026-05-25", dateLabel: "25 мая" },
  { id: "p6", image: "https://picsum.photos/seed/poidem-photo-6/400/400", title: "Караоке батл", dateKey: "2026-05-25", dateLabel: "25 мая" },
  { id: "p7", image: "https://picsum.photos/seed/poidem-photo-7/400/400", title: "Бизнес-завтрак", dateKey: "2026-05-26", dateLabel: "26 мая" },
  { id: "p8", image: "https://picsum.photos/seed/poidem-photo-8/400/400", title: "DJ вечеринка", dateKey: "2026-05-26", dateLabel: "26 мая" },
  { id: "p9", image: "https://picsum.photos/seed/poidem-photo-9/400/400", title: "Квиз", dateKey: "2026-05-28", dateLabel: "28 мая" },
  { id: "p10", image: "https://picsum.photos/seed/poidem-photo-10/400/400", title: "Живая музыка", dateKey: "2026-05-30", dateLabel: "30 мая" },
  { id: "p11", image: "https://picsum.photos/seed/poidem-photo-11/400/400", title: "Караоке батл", dateKey: "2026-06-03", dateLabel: "3 июня" },
  { id: "p12", image: "https://picsum.photos/seed/poidem-photo-12/400/400", title: "Бизнес-завтрак", dateKey: "2026-06-04", dateLabel: "4 июня" },
  { id: "p13", image: "https://picsum.photos/seed/poidem-photo-13/400/400", title: "DJ вечеринка", dateKey: "2026-06-07", dateLabel: "7 июня" },
  { id: "p14", image: "/images/gallery/karaoke-battle-start.jpg", title: "Старт караоке-батла", dateKey: "2026-06-03", dateLabel: "3 июня" },
  { id: "p15", image: "/images/gallery/karaoke-battle-contestants.jpg", title: "Участники батла", dateKey: "2026-06-03", dateLabel: "3 июня" },
  { id: "p16", image: "/images/gallery/karaoke-battle-first-song.jpg", title: "Первый номер", dateKey: "2026-06-03", dateLabel: "3 июня" },
  { id: "p17", image: "/images/gallery/karaoke-battle-prepare.jpg", title: "Подготовка к выступлению", dateKey: "2026-06-03", dateLabel: "3 июня" },
  { id: "p18", image: "/images/gallery/karaoke-battle-microphone.jpg", title: "Битва за микрофон", dateKey: "2026-06-03", dateLabel: "3 июня" },
  { id: "p19", image: "/images/gallery/karaoke-battle-stage-lights.jpg", title: "Сцена в огнях", dateKey: "2026-06-03", dateLabel: "3 июня" },
  { id: "p20", image: "/images/gallery/karaoke-battle-duet.jpg", title: "Караоке-дуэт", dateKey: "2026-06-03", dateLabel: "3 июня" },
  { id: "p21", image: "/images/gallery/karaoke-battle-hall-singing.jpg", title: "Зал подпевает", dateKey: "2026-06-03", dateLabel: "3 июня" },
  { id: "p22", image: "/images/gallery/karaoke-battle-final.jpg", title: "Финал батла", dateKey: "2026-06-03", dateLabel: "3 июня" },
  { id: "p23", image: "/images/gallery/karaoke-battle-hot-number.jpg", title: "Зажигательный номер", dateKey: "2026-06-03", dateLabel: "3 июня" },
  { id: "p24", image: "/images/gallery/karaoke-battle-atmosphere.jpg", title: "Атмосфера вечеринки", dateKey: "2026-06-03", dateLabel: "3 июня" },
  { id: "p25", image: "/images/gallery/karaoke-battle-applause.jpg", title: "Аплодисменты зала", dateKey: "2026-06-03", dateLabel: "3 июня" },
  { id: "p26", image: "/images/gallery/karaoke-battle-after-show.jpg", title: "После шоу", dateKey: "2026-06-03", dateLabel: "3 июня" },
  { id: "p27", image: "/images/gallery/karaoke-battle-guests.jpg", title: "Гости вечеринки", dateKey: "2026-06-03", dateLabel: "3 июня" },
  { id: "p28", image: "/images/gallery/karaoke-battle-party-lights.jpg", title: "Огни вечеринки", dateKey: "2026-06-03", dateLabel: "3 июня" },
  { id: "p29", image: "/images/gallery/pub-evening-june.jpg", title: "Вечер в пабе", dateKey: "2026-06-06", dateLabel: "6 июня" },
]
