import type { EventItem } from "@/types"

export const galleryPreviews: EventItem[] = [
  {
    id: "gallery-1",
    date: "24",
    month: "МАЯ",
    dayOfWeek: "Пятница",
    title: "Караоке батл",
    category: "music",
    time: "20:00",
    image: "https://picsum.photos/seed/poidem-photo-1/400/500",
    description: "Фотоотчёт с караоке-батла",
    admission: "free",
    slug: "gallery/1",
  },
  {
    id: "gallery-2",
    date: "26",
    month: "МАЯ",
    dayOfWeek: "Воскресенье",
    title: "DJ вечеринка",
    category: "music",
    time: "21:00",
    image: "https://picsum.photos/seed/poidem-photo-2/400/500",
    description: "Фотоотчёт с DJ вечеринки",
    admission: "free",
    slug: "gallery/2",
  },
  {
    id: "gallery-3",
    date: "30",
    month: "МАЯ",
    dayOfWeek: "Среда",
    title: "Живая музыка",
    category: "music",
    time: "20:00",
    image: "https://picsum.photos/seed/poidem-video-1/400/500",
    description: "Видео с выступления живой музыки",
    admission: "free",
    slug: "gallery/3",
  },
  {
    id: "gallery-4",
    date: "25",
    month: "МАЯ",
    dayOfWeek: "Суббота",
    title: "Квиз",
    category: "quiz",
    time: "21:00",
    image: "https://picsum.photos/seed/poidem-photo-3/400/500",
    description: "Фотоотчёт с квиза",
    admission: "free",
    slug: "gallery/4",
  },
  {
    id: "gallery-5",
    date: "2",
    month: "ИЮНЯ",
    dayOfWeek: "Понедельник",
    title: "Кулинарный мастер-класс",
    category: "show",
    time: "18:00",
    image: "https://picsum.photos/seed/poidem-photo-4/400/500",
    description: "Фотоотчёт с мастер-класса",
    admission: "paid",
    slug: "gallery/5",
  },
]
