import type { ServiceItem } from "@/types"

export const services: ServiceItem[] = [
  {
    id: "menu",
    icon: "utensils-crossed",
    title: "Меню",
    description: "Завтраки и блюда, кухни",
    href: "/menu",
  },
  {
    id: "schedule",
    icon: "calendar-clock",
    title: "Расписание на неделю",
    description: "События и мероприятия",
    href: "/events",
  },
  {
    id: "booking",
    icon: "phone",
    title: "Забронировать стол",
    description: "Telegram, WhatsApp, телефон",
    href: "https://wa.me/84855559797",
  },
  {
    id: "route",
    icon: "map-pin",
    title: "Как добраться",
    description: "Google Maps, Яндекс.Карты",
    href: "https://maps.google.com/?q=97+Tran+Hung+Dao+Duong+Dong+Phu+Quoc",
  },
  {
    id: "banquet",
    icon: "party-popper",
    title: "Заказать банкет или выступить",
    description: "Аренда зала, выступления, мероприятия",
    href: "/banquet",
  },
  {
    id: "promotions",
    icon: "percent",
    title: "Акции и бонусы",
    description: "Спецпредложения и бонусная программа",
    href: "/promotions",
  },
  {
    id: "hookah",
    icon: "cigarette",
    title: "Кальянное меню",
    description: "Премиальные смеси и авторские чаши",
    href: "/hookah",
  },
  {
    id: "delivery",
    icon: "truck",
    title: "Доставка блюд и кальянов",
    description: "Быстрая доставка еды и напитков",
    href: "/delivery",
  },
  {
    id: "photo-video",
    icon: "camera",
    title: "Фото, видео услуги",
    description: "Профессиональная съёмка мероприятий",
    href: "/gallery",
  },
  {
    id: "currency",
    icon: "banknote",
    title: "Обмен рублей",
    description: "Выгодный курс, быстро и безопасно",
    href: "/currency",
  },
  {
    id: "faq",
    icon: "message-circle-question",
    title: "Задать вопрос",
    description: "Мы на связи 24/7, ответим на всё",
    href: "https://t.me/poidem_pozhrem",
  },
  {
    id: "hotel",
    icon: "building",
    title: "Отель",
    description: "Комфортное проживание на Фукуоке",
    href: "/hotel",
  },
  {
    id: "community",
    icon: "users",
    title: "Сообщество",
    description: "Люди, знакомства, мероприятия, общение",
    href: "/community",
  },
  {
    id: "island-info",
    icon: "globe",
    title: "Инфо-Фукуок",
    description: "Вся полезная информация об острове",
    href: "/island-info",
  },
]
