/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from "@payloadcms/db-postgres";
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  numeric,
  boolean,
  jsonb,
  pgEnum,
} from "@payloadcms/db-postgres/drizzle/pg-core";
import { sql, relations } from "@payloadcms/db-postgres/drizzle";
export const enum_events_category = pgEnum("enum_events_category", [
  "all",
  "karaoke",
  "quiz",
  "music",
  "business",
  "show",
]);
export const enum_events_day_of_week = pgEnum("enum_events_day_of_week", [
  "Понедельник",
  "Вторник",
  "Среда",
  "Четверг",
  "Пятница",
  "Суббота",
  "Воскресенье",
]);
export const enum_events_schedule_type = pgEnum("enum_events_schedule_type", [
  "recurring",
  "one-off",
]);
export const enum_events_admission = pgEnum("enum_events_admission", [
  "free",
  "paid",
]);
export const enum_events_status = pgEnum("enum_events_status", [
  "draft",
  "published",
]);
export const enum__events_v_version_category = pgEnum(
  "enum__events_v_version_category",
  ["all", "karaoke", "quiz", "music", "business", "show"],
);
export const enum__events_v_version_day_of_week = pgEnum(
  "enum__events_v_version_day_of_week",
  [
    "Понедельник",
    "Вторник",
    "Среда",
    "Четверг",
    "Пятница",
    "Суббота",
    "Воскресенье",
  ],
);
export const enum__events_v_version_schedule_type = pgEnum(
  "enum__events_v_version_schedule_type",
  ["recurring", "one-off"],
);
export const enum__events_v_version_admission = pgEnum(
  "enum__events_v_version_admission",
  ["free", "paid"],
);
export const enum__events_v_version_status = pgEnum(
  "enum__events_v_version_status",
  ["draft", "published"],
);
export const enum_menu_categories_sections_dishes_badges_text = pgEnum(
  "enum_menu_categories_sections_dishes_badges_text",
  [
    "Премиум",
    "Веганское блюдо",
    "Вегетарианское блюдо",
    "Без добавленного сахара",
  ],
);
export const enum_menu_categories_group = pgEnum("enum_menu_categories_group", [
  "main",
  "alcohol",
  "non-alcohol",
]);
export const enum_menu_categories_status = pgEnum(
  "enum_menu_categories_status",
  ["draft", "published"],
);
export const enum__menu_categories_v_version_sections_dishes_badges_text =
  pgEnum("enum__menu_categories_v_version_sections_dishes_badges_text", [
    "Премиум",
    "Веганское блюдо",
    "Вегетарианское блюдо",
    "Без добавленного сахара",
  ]);
export const enum__menu_categories_v_version_group = pgEnum(
  "enum__menu_categories_v_version_group",
  ["main", "alcohol", "non-alcohol"],
);
export const enum__menu_categories_v_version_status = pgEnum(
  "enum__menu_categories_v_version_status",
  ["draft", "published"],
);
export const enum_gallery_videos_status = pgEnum("enum_gallery_videos_status", [
  "draft",
  "published",
]);
export const enum__gallery_videos_v_version_status = pgEnum(
  "enum__gallery_videos_v_version_status",
  ["draft", "published"],
);
export const enum_gallery_reports_category = pgEnum(
  "enum_gallery_reports_category",
  ["all", "karaoke", "quiz", "music", "business", "show"],
);
export const enum_gallery_reports_admission = pgEnum(
  "enum_gallery_reports_admission",
  ["free", "paid"],
);
export const enum_gallery_reports_status = pgEnum(
  "enum_gallery_reports_status",
  ["draft", "published"],
);
export const enum__gallery_reports_v_version_category = pgEnum(
  "enum__gallery_reports_v_version_category",
  ["all", "karaoke", "quiz", "music", "business", "show"],
);
export const enum__gallery_reports_v_version_admission = pgEnum(
  "enum__gallery_reports_v_version_admission",
  ["free", "paid"],
);
export const enum__gallery_reports_v_version_status = pgEnum(
  "enum__gallery_reports_v_version_status",
  ["draft", "published"],
);

export const users_sessions = pgTable(
  "users_sessions",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    expiresAt: timestamp("expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index("users_sessions_order_idx").on(columns._order),
    index("users_sessions_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [users.id],
      name: "users_sessions_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const users = pgTable(
  "users",
  {
    id: serial("id").primaryKey(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    email: varchar("email").notNull(),
    resetPasswordToken: varchar("reset_password_token"),
    resetPasswordExpiration: timestamp("reset_password_expiration", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar("salt"),
    hash: varchar("hash"),
    loginAttempts: numeric("login_attempts", { mode: "number" }).default(0),
    lockUntil: timestamp("lock_until", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index("users_updated_at_idx").on(columns.updatedAt),
    index("users_created_at_idx").on(columns.createdAt),
    uniqueIndex("users_email_idx").on(columns.email),
  ],
);

export const events_hero_lines = pgTable(
  "events_hero_lines",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    line: varchar("line"),
  },
  (columns) => [
    index("events_hero_lines_order_idx").on(columns._order),
    index("events_hero_lines_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [events.id],
      name: "events_hero_lines_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const events_features = pgTable(
  "events_features",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    icon: varchar("icon"),
    title: varchar("title"),
    desc: varchar("desc"),
  },
  (columns) => [
    index("events_features_order_idx").on(columns._order),
    index("events_features_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [events.id],
      name: "events_features_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const events = pgTable(
  "events",
  {
    id: serial("id").primaryKey(),
    title: varchar("title"),
    subtitle: varchar("subtitle"),
    slug: varchar("slug"),
    description: varchar("description"),
    category: enum_events_category("category").default("all"),
    date: varchar("date"),
    month: varchar("month"),
    dayOfWeek: enum_events_day_of_week("day_of_week").default("Понедельник"),
    time: varchar("time").default("20:00"),
    scheduleType:
      enum_events_schedule_type("schedule_type").default("recurring"),
    specificDate: varchar("specific_date"),
    image: integer("image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    admission: enum_events_admission("admission").default("free"),
    heroSubtitle: varchar("hero_subtitle"),
    programHeading: varchar("program_heading").default("В ПРОГРАММЕ"),
    accentColor: varchar("accent_color"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    _status: enum_events_status("_status").default("draft"),
  },
  (columns) => [
    uniqueIndex("events_slug_idx").on(columns.slug),
    index("events_image_idx").on(columns.image),
    index("events_updated_at_idx").on(columns.updatedAt),
    index("events_created_at_idx").on(columns.createdAt),
    index("events__status_idx").on(columns._status),
  ],
);

export const _events_v_version_hero_lines = pgTable(
  "_events_v_version_hero_lines",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: serial("id").primaryKey(),
    line: varchar("line"),
    _uuid: varchar("_uuid"),
  },
  (columns) => [
    index("_events_v_version_hero_lines_order_idx").on(columns._order),
    index("_events_v_version_hero_lines_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_events_v.id],
      name: "_events_v_version_hero_lines_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _events_v_version_features = pgTable(
  "_events_v_version_features",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: serial("id").primaryKey(),
    icon: varchar("icon"),
    title: varchar("title"),
    desc: varchar("desc"),
    _uuid: varchar("_uuid"),
  },
  (columns) => [
    index("_events_v_version_features_order_idx").on(columns._order),
    index("_events_v_version_features_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_events_v.id],
      name: "_events_v_version_features_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _events_v = pgTable(
  "_events_v",
  {
    id: serial("id").primaryKey(),
    parent: integer("parent_id").references(() => events.id, {
      onDelete: "set null",
    }),
    version_title: varchar("version_title"),
    version_subtitle: varchar("version_subtitle"),
    version_slug: varchar("version_slug"),
    version_description: varchar("version_description"),
    version_category:
      enum__events_v_version_category("version_category").default("all"),
    version_date: varchar("version_date"),
    version_month: varchar("version_month"),
    version_dayOfWeek: enum__events_v_version_day_of_week(
      "version_day_of_week",
    ).default("Понедельник"),
    version_time: varchar("version_time").default("20:00"),
    version_scheduleType: enum__events_v_version_schedule_type(
      "version_schedule_type",
    ).default("recurring"),
    version_specificDate: varchar("version_specific_date"),
    version_image: integer("version_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    version_admission:
      enum__events_v_version_admission("version_admission").default("free"),
    version_heroSubtitle: varchar("version_hero_subtitle"),
    version_programHeading: varchar("version_program_heading").default(
      "В ПРОГРАММЕ",
    ),
    version_accentColor: varchar("version_accent_color"),
    version_updatedAt: timestamp("version_updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp("version_created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version__status:
      enum__events_v_version_status("version__status").default("draft"),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    latest: boolean("latest"),
  },
  (columns) => [
    index("_events_v_parent_idx").on(columns.parent),
    index("_events_v_version_version_slug_idx").on(columns.version_slug),
    index("_events_v_version_version_image_idx").on(columns.version_image),
    index("_events_v_version_version_updated_at_idx").on(
      columns.version_updatedAt,
    ),
    index("_events_v_version_version_created_at_idx").on(
      columns.version_createdAt,
    ),
    index("_events_v_version_version__status_idx").on(columns.version__status),
    index("_events_v_created_at_idx").on(columns.createdAt),
    index("_events_v_updated_at_idx").on(columns.updatedAt),
    index("_events_v_latest_idx").on(columns.latest),
  ],
);

export const menu_categories_sections_dishes_badges = pgTable(
  "menu_categories_sections_dishes_badges",
  {
    _order: integer("_order").notNull(),
    _parentID: varchar("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    text: enum_menu_categories_sections_dishes_badges_text("text"),
  },
  (columns) => [
    index("menu_categories_sections_dishes_badges_order_idx").on(
      columns._order,
    ),
    index("menu_categories_sections_dishes_badges_parent_id_idx").on(
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [menu_categories_sections_dishes.id],
      name: "menu_categories_sections_dishes_badges_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const menu_categories_sections_dishes = pgTable(
  "menu_categories_sections_dishes",
  {
    _order: integer("_order").notNull(),
    _parentID: varchar("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    name: varchar("name"),
    description: varchar("description"),
    subtitle: varchar("subtitle"),
    base: varchar("base"),
    composition: varchar("composition"),
    weight: varchar("weight"),
    price: varchar("price"),
    discount: numeric("discount", { mode: "number" }),
  },
  (columns) => [
    index("menu_categories_sections_dishes_order_idx").on(columns._order),
    index("menu_categories_sections_dishes_parent_id_idx").on(
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [menu_categories_sections.id],
      name: "menu_categories_sections_dishes_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const menu_categories_sections = pgTable(
  "menu_categories_sections",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    title: varchar("title"),
    subtitle: varchar("subtitle"),
  },
  (columns) => [
    index("menu_categories_sections_order_idx").on(columns._order),
    index("menu_categories_sections_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [menu_categories.id],
      name: "menu_categories_sections_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const menu_categories = pgTable(
  "menu_categories",
  {
    id: serial("id").primaryKey(),
    slug: varchar("slug"),
    title: varchar("title"),
    subtitle: varchar("subtitle"),
    image: integer("image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    group: enum_menu_categories_group("group").default("main"),
    order: numeric("order", { mode: "number" }).default(0),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    _status: enum_menu_categories_status("_status").default("draft"),
  },
  (columns) => [
    uniqueIndex("menu_categories_slug_idx").on(columns.slug),
    index("menu_categories_image_idx").on(columns.image),
    index("menu_categories_updated_at_idx").on(columns.updatedAt),
    index("menu_categories_created_at_idx").on(columns.createdAt),
    index("menu_categories__status_idx").on(columns._status),
  ],
);

export const _menu_categories_v_version_sections_dishes_badges = pgTable(
  "_menu_categories_v_version_sections_dishes_badges",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: serial("id").primaryKey(),
    text: enum__menu_categories_v_version_sections_dishes_badges_text("text"),
    _uuid: varchar("_uuid"),
  },
  (columns) => [
    index("_menu_categories_v_version_sections_dishes_badges_order_idx").on(
      columns._order,
    ),
    index("_menu_categories_v_version_sections_dishes_badges_parent_id_idx").on(
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_menu_categories_v_version_sections_dishes.id],
      name: "_menu_categories_v_version_sections_dishes_badges_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _menu_categories_v_version_sections_dishes = pgTable(
  "_menu_categories_v_version_sections_dishes",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: serial("id").primaryKey(),
    name: varchar("name"),
    description: varchar("description"),
    subtitle: varchar("subtitle"),
    base: varchar("base"),
    composition: varchar("composition"),
    weight: varchar("weight"),
    price: varchar("price"),
    discount: numeric("discount", { mode: "number" }),
    _uuid: varchar("_uuid"),
  },
  (columns) => [
    index("_menu_categories_v_version_sections_dishes_order_idx").on(
      columns._order,
    ),
    index("_menu_categories_v_version_sections_dishes_parent_id_idx").on(
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_menu_categories_v_version_sections.id],
      name: "_menu_categories_v_version_sections_dishes_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _menu_categories_v_version_sections = pgTable(
  "_menu_categories_v_version_sections",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: serial("id").primaryKey(),
    title: varchar("title"),
    subtitle: varchar("subtitle"),
    _uuid: varchar("_uuid"),
  },
  (columns) => [
    index("_menu_categories_v_version_sections_order_idx").on(columns._order),
    index("_menu_categories_v_version_sections_parent_id_idx").on(
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_menu_categories_v.id],
      name: "_menu_categories_v_version_sections_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _menu_categories_v = pgTable(
  "_menu_categories_v",
  {
    id: serial("id").primaryKey(),
    parent: integer("parent_id").references(() => menu_categories.id, {
      onDelete: "set null",
    }),
    version_slug: varchar("version_slug"),
    version_title: varchar("version_title"),
    version_subtitle: varchar("version_subtitle"),
    version_image: integer("version_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    version_group:
      enum__menu_categories_v_version_group("version_group").default("main"),
    version_order: numeric("version_order", { mode: "number" }).default(0),
    version_updatedAt: timestamp("version_updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp("version_created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version__status:
      enum__menu_categories_v_version_status("version__status").default(
        "draft",
      ),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    latest: boolean("latest"),
  },
  (columns) => [
    index("_menu_categories_v_parent_idx").on(columns.parent),
    index("_menu_categories_v_version_version_slug_idx").on(
      columns.version_slug,
    ),
    index("_menu_categories_v_version_version_image_idx").on(
      columns.version_image,
    ),
    index("_menu_categories_v_version_version_updated_at_idx").on(
      columns.version_updatedAt,
    ),
    index("_menu_categories_v_version_version_created_at_idx").on(
      columns.version_createdAt,
    ),
    index("_menu_categories_v_version_version__status_idx").on(
      columns.version__status,
    ),
    index("_menu_categories_v_created_at_idx").on(columns.createdAt),
    index("_menu_categories_v_updated_at_idx").on(columns.updatedAt),
    index("_menu_categories_v_latest_idx").on(columns.latest),
  ],
);

export const gallery_videos_videos = pgTable(
  "gallery_videos_videos",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    title: varchar("title"),
    videoUrl: varchar("video_url"),
    videoId: varchar("video_id"),
  },
  (columns) => [
    index("gallery_videos_videos_order_idx").on(columns._order),
    index("gallery_videos_videos_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [gallery_videos.id],
      name: "gallery_videos_videos_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const gallery_videos = pgTable(
  "gallery_videos",
  {
    id: serial("id").primaryKey(),
    title: varchar("title"),
    videoId: varchar("video_id"),
    reportDate: varchar("report_date"),
    dateKey: varchar("date_key"),
    dateLabel: varchar("date_label"),
    order: numeric("order", { mode: "number" }).default(0),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    _status: enum_gallery_videos_status("_status").default("draft"),
  },
  (columns) => [
    index("gallery_videos_updated_at_idx").on(columns.updatedAt),
    index("gallery_videos_created_at_idx").on(columns.createdAt),
    index("gallery_videos__status_idx").on(columns._status),
  ],
);

export const _gallery_videos_v_version_videos = pgTable(
  "_gallery_videos_v_version_videos",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: serial("id").primaryKey(),
    title: varchar("title"),
    videoUrl: varchar("video_url"),
    videoId: varchar("video_id"),
    _uuid: varchar("_uuid"),
  },
  (columns) => [
    index("_gallery_videos_v_version_videos_order_idx").on(columns._order),
    index("_gallery_videos_v_version_videos_parent_id_idx").on(
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_gallery_videos_v.id],
      name: "_gallery_videos_v_version_videos_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _gallery_videos_v = pgTable(
  "_gallery_videos_v",
  {
    id: serial("id").primaryKey(),
    parent: integer("parent_id").references(() => gallery_videos.id, {
      onDelete: "set null",
    }),
    version_title: varchar("version_title"),
    version_videoId: varchar("version_video_id"),
    version_reportDate: varchar("version_report_date"),
    version_dateKey: varchar("version_date_key"),
    version_dateLabel: varchar("version_date_label"),
    version_order: numeric("version_order", { mode: "number" }).default(0),
    version_updatedAt: timestamp("version_updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp("version_created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version__status:
      enum__gallery_videos_v_version_status("version__status").default("draft"),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    latest: boolean("latest"),
  },
  (columns) => [
    index("_gallery_videos_v_parent_idx").on(columns.parent),
    index("_gallery_videos_v_version_version_updated_at_idx").on(
      columns.version_updatedAt,
    ),
    index("_gallery_videos_v_version_version_created_at_idx").on(
      columns.version_createdAt,
    ),
    index("_gallery_videos_v_version_version__status_idx").on(
      columns.version__status,
    ),
    index("_gallery_videos_v_created_at_idx").on(columns.createdAt),
    index("_gallery_videos_v_updated_at_idx").on(columns.updatedAt),
    index("_gallery_videos_v_latest_idx").on(columns.latest),
  ],
);

export const gallery_reports_photos = pgTable(
  "gallery_reports_photos",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    title: varchar("title"),
    image: integer("image_id").references(() => media.id, {
      onDelete: "set null",
    }),
  },
  (columns) => [
    index("gallery_reports_photos_order_idx").on(columns._order),
    index("gallery_reports_photos_parent_id_idx").on(columns._parentID),
    index("gallery_reports_photos_image_idx").on(columns.image),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [gallery_reports.id],
      name: "gallery_reports_photos_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const gallery_reports = pgTable(
  "gallery_reports",
  {
    id: serial("id").primaryKey(),
    title: varchar("title"),
    slug: varchar("slug"),
    description: varchar("description"),
    category: enum_gallery_reports_category("category").default("all"),
    reportDate: varchar("report_date"),
    date: varchar("date"),
    month: varchar("month"),
    dayOfWeek: varchar("day_of_week"),
    time: varchar("time").default("20:00"),
    image: integer("image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    admission: enum_gallery_reports_admission("admission").default("free"),
    order: numeric("order", { mode: "number" }).default(0),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    _status: enum_gallery_reports_status("_status").default("draft"),
  },
  (columns) => [
    uniqueIndex("gallery_reports_slug_idx").on(columns.slug),
    index("gallery_reports_image_idx").on(columns.image),
    index("gallery_reports_updated_at_idx").on(columns.updatedAt),
    index("gallery_reports_created_at_idx").on(columns.createdAt),
    index("gallery_reports__status_idx").on(columns._status),
  ],
);

export const _gallery_reports_v_version_photos = pgTable(
  "_gallery_reports_v_version_photos",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: serial("id").primaryKey(),
    title: varchar("title"),
    image: integer("image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    _uuid: varchar("_uuid"),
  },
  (columns) => [
    index("_gallery_reports_v_version_photos_order_idx").on(columns._order),
    index("_gallery_reports_v_version_photos_parent_id_idx").on(
      columns._parentID,
    ),
    index("_gallery_reports_v_version_photos_image_idx").on(columns.image),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_gallery_reports_v.id],
      name: "_gallery_reports_v_version_photos_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _gallery_reports_v = pgTable(
  "_gallery_reports_v",
  {
    id: serial("id").primaryKey(),
    parent: integer("parent_id").references(() => gallery_reports.id, {
      onDelete: "set null",
    }),
    version_title: varchar("version_title"),
    version_slug: varchar("version_slug"),
    version_description: varchar("version_description"),
    version_category:
      enum__gallery_reports_v_version_category("version_category").default(
        "all",
      ),
    version_reportDate: varchar("version_report_date"),
    version_date: varchar("version_date"),
    version_month: varchar("version_month"),
    version_dayOfWeek: varchar("version_day_of_week"),
    version_time: varchar("version_time").default("20:00"),
    version_image: integer("version_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    version_admission:
      enum__gallery_reports_v_version_admission("version_admission").default(
        "free",
      ),
    version_order: numeric("version_order", { mode: "number" }).default(0),
    version_updatedAt: timestamp("version_updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp("version_created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version__status:
      enum__gallery_reports_v_version_status("version__status").default(
        "draft",
      ),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    latest: boolean("latest"),
  },
  (columns) => [
    index("_gallery_reports_v_parent_idx").on(columns.parent),
    index("_gallery_reports_v_version_version_slug_idx").on(
      columns.version_slug,
    ),
    index("_gallery_reports_v_version_version_image_idx").on(
      columns.version_image,
    ),
    index("_gallery_reports_v_version_version_updated_at_idx").on(
      columns.version_updatedAt,
    ),
    index("_gallery_reports_v_version_version_created_at_idx").on(
      columns.version_createdAt,
    ),
    index("_gallery_reports_v_version_version__status_idx").on(
      columns.version__status,
    ),
    index("_gallery_reports_v_created_at_idx").on(columns.createdAt),
    index("_gallery_reports_v_updated_at_idx").on(columns.updatedAt),
    index("_gallery_reports_v_latest_idx").on(columns.latest),
  ],
);

export const media = pgTable(
  "media",
  {
    id: serial("id").primaryKey(),
    alt: varchar("alt").notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    url: varchar("url"),
    thumbnailURL: varchar("thumbnail_u_r_l"),
    filename: varchar("filename"),
    mimeType: varchar("mime_type"),
    filesize: numeric("filesize", { mode: "number" }),
    width: numeric("width", { mode: "number" }),
    height: numeric("height", { mode: "number" }),
    focalX: numeric("focal_x", { mode: "number" }),
    focalY: numeric("focal_y", { mode: "number" }),
    sizes_thumbnail_url: varchar("sizes_thumbnail_url"),
    sizes_thumbnail_width: numeric("sizes_thumbnail_width", { mode: "number" }),
    sizes_thumbnail_height: numeric("sizes_thumbnail_height", {
      mode: "number",
    }),
    sizes_thumbnail_mimeType: varchar("sizes_thumbnail_mime_type"),
    sizes_thumbnail_filesize: numeric("sizes_thumbnail_filesize", {
      mode: "number",
    }),
    sizes_thumbnail_filename: varchar("sizes_thumbnail_filename"),
    sizes_card_url: varchar("sizes_card_url"),
    sizes_card_width: numeric("sizes_card_width", { mode: "number" }),
    sizes_card_height: numeric("sizes_card_height", { mode: "number" }),
    sizes_card_mimeType: varchar("sizes_card_mime_type"),
    sizes_card_filesize: numeric("sizes_card_filesize", { mode: "number" }),
    sizes_card_filename: varchar("sizes_card_filename"),
    sizes_hero_url: varchar("sizes_hero_url"),
    sizes_hero_width: numeric("sizes_hero_width", { mode: "number" }),
    sizes_hero_height: numeric("sizes_hero_height", { mode: "number" }),
    sizes_hero_mimeType: varchar("sizes_hero_mime_type"),
    sizes_hero_filesize: numeric("sizes_hero_filesize", { mode: "number" }),
    sizes_hero_filename: varchar("sizes_hero_filename"),
  },
  (columns) => [
    index("media_updated_at_idx").on(columns.updatedAt),
    index("media_created_at_idx").on(columns.createdAt),
    uniqueIndex("media_filename_idx").on(columns.filename),
    index("media_sizes_thumbnail_sizes_thumbnail_filename_idx").on(
      columns.sizes_thumbnail_filename,
    ),
    index("media_sizes_card_sizes_card_filename_idx").on(
      columns.sizes_card_filename,
    ),
    index("media_sizes_hero_sizes_hero_filename_idx").on(
      columns.sizes_hero_filename,
    ),
  ],
);

export const _media_v = pgTable(
  "_media_v",
  {
    id: serial("id").primaryKey(),
    parent: integer("parent_id").references(() => media.id, {
      onDelete: "set null",
    }),
    version_alt: varchar("version_alt").notNull(),
    version_updatedAt: timestamp("version_updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp("version_created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_url: varchar("version_url"),
    version_thumbnailURL: varchar("version_thumbnail_u_r_l"),
    version_filename: varchar("version_filename"),
    version_mimeType: varchar("version_mime_type"),
    version_filesize: numeric("version_filesize", { mode: "number" }),
    version_width: numeric("version_width", { mode: "number" }),
    version_height: numeric("version_height", { mode: "number" }),
    version_focalX: numeric("version_focal_x", { mode: "number" }),
    version_focalY: numeric("version_focal_y", { mode: "number" }),
    version_sizes_thumbnail_url: varchar("version_sizes_thumbnail_url"),
    version_sizes_thumbnail_width: numeric("version_sizes_thumbnail_width", {
      mode: "number",
    }),
    version_sizes_thumbnail_height: numeric("version_sizes_thumbnail_height", {
      mode: "number",
    }),
    version_sizes_thumbnail_mimeType: varchar(
      "version_sizes_thumbnail_mime_type",
    ),
    version_sizes_thumbnail_filesize: numeric(
      "version_sizes_thumbnail_filesize",
      { mode: "number" },
    ),
    version_sizes_thumbnail_filename: varchar(
      "version_sizes_thumbnail_filename",
    ),
    version_sizes_card_url: varchar("version_sizes_card_url"),
    version_sizes_card_width: numeric("version_sizes_card_width", {
      mode: "number",
    }),
    version_sizes_card_height: numeric("version_sizes_card_height", {
      mode: "number",
    }),
    version_sizes_card_mimeType: varchar("version_sizes_card_mime_type"),
    version_sizes_card_filesize: numeric("version_sizes_card_filesize", {
      mode: "number",
    }),
    version_sizes_card_filename: varchar("version_sizes_card_filename"),
    version_sizes_hero_url: varchar("version_sizes_hero_url"),
    version_sizes_hero_width: numeric("version_sizes_hero_width", {
      mode: "number",
    }),
    version_sizes_hero_height: numeric("version_sizes_hero_height", {
      mode: "number",
    }),
    version_sizes_hero_mimeType: varchar("version_sizes_hero_mime_type"),
    version_sizes_hero_filesize: numeric("version_sizes_hero_filesize", {
      mode: "number",
    }),
    version_sizes_hero_filename: varchar("version_sizes_hero_filename"),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("_media_v_parent_idx").on(columns.parent),
    index("_media_v_version_version_updated_at_idx").on(
      columns.version_updatedAt,
    ),
    index("_media_v_version_version_created_at_idx").on(
      columns.version_createdAt,
    ),
    index("_media_v_version_version_filename_idx").on(columns.version_filename),
    index("_media_v_version_sizes_thumbnail_version_sizes_thumbnail_idx").on(
      columns.version_sizes_thumbnail_filename,
    ),
    index("_media_v_version_sizes_card_version_sizes_card_filename_idx").on(
      columns.version_sizes_card_filename,
    ),
    index("_media_v_version_sizes_hero_version_sizes_hero_filename_idx").on(
      columns.version_sizes_hero_filename,
    ),
    index("_media_v_created_at_idx").on(columns.createdAt),
    index("_media_v_updated_at_idx").on(columns.updatedAt),
  ],
);

export const payload_kv = pgTable(
  "payload_kv",
  {
    id: serial("id").primaryKey(),
    key: varchar("key").notNull(),
    data: jsonb("data").notNull(),
  },
  (columns) => [uniqueIndex("payload_kv_key_idx").on(columns.key)],
);

export const payload_locked_documents = pgTable(
  "payload_locked_documents",
  {
    id: serial("id").primaryKey(),
    globalSlug: varchar("global_slug"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_locked_documents_global_slug_idx").on(columns.globalSlug),
    index("payload_locked_documents_updated_at_idx").on(columns.updatedAt),
    index("payload_locked_documents_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents_rels = pgTable(
  "payload_locked_documents_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
    eventsID: integer("events_id"),
    "menu-categoriesID": integer("menu_categories_id"),
    "gallery-videosID": integer("gallery_videos_id"),
    "gallery-reportsID": integer("gallery_reports_id"),
    mediaID: integer("media_id"),
  },
  (columns) => [
    index("payload_locked_documents_rels_order_idx").on(columns.order),
    index("payload_locked_documents_rels_parent_idx").on(columns.parent),
    index("payload_locked_documents_rels_path_idx").on(columns.path),
    index("payload_locked_documents_rels_users_id_idx").on(columns.usersID),
    index("payload_locked_documents_rels_events_id_idx").on(columns.eventsID),
    index("payload_locked_documents_rels_menu_categories_id_idx").on(
      columns["menu-categoriesID"],
    ),
    index("payload_locked_documents_rels_gallery_videos_id_idx").on(
      columns["gallery-videosID"],
    ),
    index("payload_locked_documents_rels_gallery_reports_id_idx").on(
      columns["gallery-reportsID"],
    ),
    index("payload_locked_documents_rels_media_id_idx").on(columns.mediaID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_locked_documents_rels_users_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["eventsID"]],
      foreignColumns: [events.id],
      name: "payload_locked_documents_rels_events_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["menu-categoriesID"]],
      foreignColumns: [menu_categories.id],
      name: "payload_locked_documents_rels_menu_categories_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["gallery-videosID"]],
      foreignColumns: [gallery_videos.id],
      name: "payload_locked_documents_rels_gallery_videos_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["gallery-reportsID"]],
      foreignColumns: [gallery_reports.id],
      name: "payload_locked_documents_rels_gallery_reports_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "payload_locked_documents_rels_media_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_preferences = pgTable(
  "payload_preferences",
  {
    id: serial("id").primaryKey(),
    key: varchar("key"),
    value: jsonb("value"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_preferences_key_idx").on(columns.key),
    index("payload_preferences_updated_at_idx").on(columns.updatedAt),
    index("payload_preferences_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_preferences_rels = pgTable(
  "payload_preferences_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
  },
  (columns) => [
    index("payload_preferences_rels_order_idx").on(columns.order),
    index("payload_preferences_rels_parent_idx").on(columns.parent),
    index("payload_preferences_rels_path_idx").on(columns.path),
    index("payload_preferences_rels_users_id_idx").on(columns.usersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_preferences_rels_users_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_migrations = pgTable(
  "payload_migrations",
  {
    id: serial("id").primaryKey(),
    name: varchar("name"),
    batch: numeric("batch", { mode: "number" }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_migrations_updated_at_idx").on(columns.updatedAt),
    index("payload_migrations_created_at_idx").on(columns.createdAt),
  ],
);

export const settings = pgTable("settings", {
  id: serial("id").primaryKey(),
  siteName: varchar("site_name").default("POIDEM POZHREM!"),
  tagline: varchar("tagline").default(
    "Ресторан на Фукуоке, где каждый день что-то происходит!",
  ),
  description: varchar("description").default(
    "Сообщество и поддержка русскоязычных на Фукуоке",
  ),
  footerHeart: varchar("footer_heart").default(
    "POIDEM POZHREM — в этом ресторане реально жизнь становится вкусной!",
  ),
  cuisines: varchar("cuisines").default(
    "РУССКАЯ • КАВКАЗСКАЯ • ВОСТОЧНАЯ • ЕВРОПЕЙСКАЯ • АЗИАТСКАЯ КУХНЯ",
  ),
  neonSlogan_line1: varchar("neon_slogan_line1").default("Я ВЫБИРАЮ"),
  neonSlogan_accent1: varchar("neon_slogan_accent1").default("ВКУСНО"),
  neonSlogan_accent2: varchar("neon_slogan_accent2").default("ЖИТЬ!"),
  neonSlogan_subtitle: varchar("neon_slogan_subtitle").default(
    "И ЭТО ЛУЧШЕЕ РЕШЕНИЕ СЕГОДНЯ",
  ),
  phone: varchar("phone").default("+84 783 779 879"),
  phoneHref: varchar("phone_href").default("tel:+84783779879"),
  email: varchar("email").default("poidempozhrem@gmail.com"),
  address: varchar("address").default("97 Trần Hưng Đạo, Dương Đông, Phú Quốc"),
  addressFull: varchar("address_full").default(
    "97 Trần Hưng Đạo, Дương Đông, Phú Quốc, 2 этаж (вход через Holiday Center)",
  ),
  telegram: varchar("telegram").default("https://t.me/poidem_pozhrem"),
  telegramBot: varchar("telegram_bot").default(
    "https://t.me/poidem_pozhrem_bot",
  ),
  whatsapp: varchar("whatsapp").default("https://wa.me/84783779879"),
  instagram: varchar("instagram").default(
    "https://instagram.com/poidem_po_zhrem",
  ),
  facebook: varchar("facebook").default("https://facebook.com/PoidemPozhrem"),
  youtube: varchar("youtube").default("https://youtube.com/@poidempozhrEM"),
  tiktok: varchar("tiktok").default("https://tiktok.com/@poidem_pozhrem"),
  zalo: varchar("zalo").default("https://zalo.me/84783779879"),
  googleMaps: varchar("google_maps").default(
    "https://maps.google.com/?q=97+Tran+Hung+Dao+Duong+Dong+Phu+Quoc",
  ),
  yandexMaps: varchar("yandex_maps").default(
    "https://yandex.ru/maps/?pt=103.9530,10.2100&z=17&l=map",
  ),
  grab: varchar("grab").default(
    "https://r.grab.com/g/6-20260801_223246_0BD425829C55464F9ACF75301A16722E_MEXMPS-5-C76UNTW3VLBDTT",
  ),
  workingHours_label: varchar("working_hours_label").default("Ежедневно"),
  workingHours_hours: varchar("working_hours_hours").default("24/7"),
  workingHours_highlighted: boolean("working_hours_highlighted").default(true),
  updatedAt: timestamp("updated_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
  createdAt: timestamp("created_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
});

export const home_content_services = pgTable(
  "home_content_services",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    icon: varchar("icon"),
    title: varchar("title").notNull(),
    description: varchar("description").notNull(),
    href: varchar("href").notNull(),
  },
  (columns) => [
    index("home_content_services_order_idx").on(columns._order),
    index("home_content_services_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [home_content.id],
      name: "home_content_services_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const home_content_quick_nav = pgTable(
  "home_content_quick_nav",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    icon: varchar("icon").notNull(),
    label: varchar("label").notNull(),
    desc: varchar("desc").notNull(),
    href: varchar("href").notNull(),
  },
  (columns) => [
    index("home_content_quick_nav_order_idx").on(columns._order),
    index("home_content_quick_nav_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [home_content.id],
      name: "home_content_quick_nav_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const home_content = pgTable("home_content", {
  id: serial("id").primaryKey(),
  title_text: varchar("title_text").default(
    "Ресторан на Фукуоке, где каждый день",
  ),
  title_accent: varchar("title_accent").default("что-то происходит!"),
  cuisines: varchar("cuisines").default(
    "РУССКАЯ • КАВКАЗСКАЯ • ВОСТОЧНАЯ • ЕВРОПЕЙСКАЯ • АЗИАТСКАЯ КУХНЯ",
  ),
  neonSlogan_line1: varchar("neon_slogan_line1").default("Я ВЫБИРАЮ"),
  neonSlogan_accent1: varchar("neon_slogan_accent1").default("ВКУСНО"),
  neonSlogan_accent2: varchar("neon_slogan_accent2").default("ЖИТЬ!"),
  neonSlogan_subtitle: varchar("neon_slogan_subtitle").default(
    "И ЭТО ЛУЧШЕЕ РЕШЕНИЕ СЕГОДНЯ",
  ),
  menuTitle: varchar("menu_title").default("МЕНЮ"),
  eventsTitle: varchar("events_title").default("РАСПИСАНИЕ НА НЕДЕЛЮ"),
  galleryTitle: varchar("gallery_title").default("ФОТО И ВИДЕООТЧЁТЫ"),
  updatedAt: timestamp("updated_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
  createdAt: timestamp("created_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
});

export const home_content_rels = pgTable(
  "home_content_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    "gallery-reportsID": integer("gallery_reports_id"),
    "gallery-videosID": integer("gallery_videos_id"),
  },
  (columns) => [
    index("home_content_rels_order_idx").on(columns.order),
    index("home_content_rels_parent_idx").on(columns.parent),
    index("home_content_rels_path_idx").on(columns.path),
    index("home_content_rels_gallery_reports_id_idx").on(
      columns["gallery-reportsID"],
    ),
    index("home_content_rels_gallery_videos_id_idx").on(
      columns["gallery-videosID"],
    ),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [home_content.id],
      name: "home_content_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["gallery-reportsID"]],
      foreignColumns: [gallery_reports.id],
      name: "home_content_rels_gallery_reports_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["gallery-videosID"]],
      foreignColumns: [gallery_videos.id],
      name: "home_content_rels_gallery_videos_fk",
    }).onDelete("cascade"),
  ],
);

export const relations_users_sessions = relations(
  users_sessions,
  ({ one }) => ({
    _parentID: one(users, {
      fields: [users_sessions._parentID],
      references: [users.id],
      relationName: "sessions",
    }),
  }),
);
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: "sessions",
  }),
}));
export const relations_events_hero_lines = relations(
  events_hero_lines,
  ({ one }) => ({
    _parentID: one(events, {
      fields: [events_hero_lines._parentID],
      references: [events.id],
      relationName: "heroLines",
    }),
  }),
);
export const relations_events_features = relations(
  events_features,
  ({ one }) => ({
    _parentID: one(events, {
      fields: [events_features._parentID],
      references: [events.id],
      relationName: "features",
    }),
  }),
);
export const relations_events = relations(events, ({ one, many }) => ({
  image: one(media, {
    fields: [events.image],
    references: [media.id],
    relationName: "image",
  }),
  heroLines: many(events_hero_lines, {
    relationName: "heroLines",
  }),
  features: many(events_features, {
    relationName: "features",
  }),
}));
export const relations__events_v_version_hero_lines = relations(
  _events_v_version_hero_lines,
  ({ one }) => ({
    _parentID: one(_events_v, {
      fields: [_events_v_version_hero_lines._parentID],
      references: [_events_v.id],
      relationName: "version_heroLines",
    }),
  }),
);
export const relations__events_v_version_features = relations(
  _events_v_version_features,
  ({ one }) => ({
    _parentID: one(_events_v, {
      fields: [_events_v_version_features._parentID],
      references: [_events_v.id],
      relationName: "version_features",
    }),
  }),
);
export const relations__events_v = relations(_events_v, ({ one, many }) => ({
  parent: one(events, {
    fields: [_events_v.parent],
    references: [events.id],
    relationName: "parent",
  }),
  version_image: one(media, {
    fields: [_events_v.version_image],
    references: [media.id],
    relationName: "version_image",
  }),
  version_heroLines: many(_events_v_version_hero_lines, {
    relationName: "version_heroLines",
  }),
  version_features: many(_events_v_version_features, {
    relationName: "version_features",
  }),
}));
export const relations_menu_categories_sections_dishes_badges = relations(
  menu_categories_sections_dishes_badges,
  ({ one }) => ({
    _parentID: one(menu_categories_sections_dishes, {
      fields: [menu_categories_sections_dishes_badges._parentID],
      references: [menu_categories_sections_dishes.id],
      relationName: "badges",
    }),
  }),
);
export const relations_menu_categories_sections_dishes = relations(
  menu_categories_sections_dishes,
  ({ one, many }) => ({
    _parentID: one(menu_categories_sections, {
      fields: [menu_categories_sections_dishes._parentID],
      references: [menu_categories_sections.id],
      relationName: "dishes",
    }),
    badges: many(menu_categories_sections_dishes_badges, {
      relationName: "badges",
    }),
  }),
);
export const relations_menu_categories_sections = relations(
  menu_categories_sections,
  ({ one, many }) => ({
    _parentID: one(menu_categories, {
      fields: [menu_categories_sections._parentID],
      references: [menu_categories.id],
      relationName: "sections",
    }),
    dishes: many(menu_categories_sections_dishes, {
      relationName: "dishes",
    }),
  }),
);
export const relations_menu_categories = relations(
  menu_categories,
  ({ one, many }) => ({
    image: one(media, {
      fields: [menu_categories.image],
      references: [media.id],
      relationName: "image",
    }),
    sections: many(menu_categories_sections, {
      relationName: "sections",
    }),
  }),
);
export const relations__menu_categories_v_version_sections_dishes_badges =
  relations(_menu_categories_v_version_sections_dishes_badges, ({ one }) => ({
    _parentID: one(_menu_categories_v_version_sections_dishes, {
      fields: [_menu_categories_v_version_sections_dishes_badges._parentID],
      references: [_menu_categories_v_version_sections_dishes.id],
      relationName: "badges",
    }),
  }));
export const relations__menu_categories_v_version_sections_dishes = relations(
  _menu_categories_v_version_sections_dishes,
  ({ one, many }) => ({
    _parentID: one(_menu_categories_v_version_sections, {
      fields: [_menu_categories_v_version_sections_dishes._parentID],
      references: [_menu_categories_v_version_sections.id],
      relationName: "dishes",
    }),
    badges: many(_menu_categories_v_version_sections_dishes_badges, {
      relationName: "badges",
    }),
  }),
);
export const relations__menu_categories_v_version_sections = relations(
  _menu_categories_v_version_sections,
  ({ one, many }) => ({
    _parentID: one(_menu_categories_v, {
      fields: [_menu_categories_v_version_sections._parentID],
      references: [_menu_categories_v.id],
      relationName: "version_sections",
    }),
    dishes: many(_menu_categories_v_version_sections_dishes, {
      relationName: "dishes",
    }),
  }),
);
export const relations__menu_categories_v = relations(
  _menu_categories_v,
  ({ one, many }) => ({
    parent: one(menu_categories, {
      fields: [_menu_categories_v.parent],
      references: [menu_categories.id],
      relationName: "parent",
    }),
    version_image: one(media, {
      fields: [_menu_categories_v.version_image],
      references: [media.id],
      relationName: "version_image",
    }),
    version_sections: many(_menu_categories_v_version_sections, {
      relationName: "version_sections",
    }),
  }),
);
export const relations_gallery_videos_videos = relations(
  gallery_videos_videos,
  ({ one }) => ({
    _parentID: one(gallery_videos, {
      fields: [gallery_videos_videos._parentID],
      references: [gallery_videos.id],
      relationName: "videos",
    }),
  }),
);
export const relations_gallery_videos = relations(
  gallery_videos,
  ({ many }) => ({
    videos: many(gallery_videos_videos, {
      relationName: "videos",
    }),
  }),
);
export const relations__gallery_videos_v_version_videos = relations(
  _gallery_videos_v_version_videos,
  ({ one }) => ({
    _parentID: one(_gallery_videos_v, {
      fields: [_gallery_videos_v_version_videos._parentID],
      references: [_gallery_videos_v.id],
      relationName: "version_videos",
    }),
  }),
);
export const relations__gallery_videos_v = relations(
  _gallery_videos_v,
  ({ one, many }) => ({
    parent: one(gallery_videos, {
      fields: [_gallery_videos_v.parent],
      references: [gallery_videos.id],
      relationName: "parent",
    }),
    version_videos: many(_gallery_videos_v_version_videos, {
      relationName: "version_videos",
    }),
  }),
);
export const relations_gallery_reports_photos = relations(
  gallery_reports_photos,
  ({ one }) => ({
    _parentID: one(gallery_reports, {
      fields: [gallery_reports_photos._parentID],
      references: [gallery_reports.id],
      relationName: "photos",
    }),
    image: one(media, {
      fields: [gallery_reports_photos.image],
      references: [media.id],
      relationName: "image",
    }),
  }),
);
export const relations_gallery_reports = relations(
  gallery_reports,
  ({ one, many }) => ({
    image: one(media, {
      fields: [gallery_reports.image],
      references: [media.id],
      relationName: "image",
    }),
    photos: many(gallery_reports_photos, {
      relationName: "photos",
    }),
  }),
);
export const relations__gallery_reports_v_version_photos = relations(
  _gallery_reports_v_version_photos,
  ({ one }) => ({
    _parentID: one(_gallery_reports_v, {
      fields: [_gallery_reports_v_version_photos._parentID],
      references: [_gallery_reports_v.id],
      relationName: "version_photos",
    }),
    image: one(media, {
      fields: [_gallery_reports_v_version_photos.image],
      references: [media.id],
      relationName: "image",
    }),
  }),
);
export const relations__gallery_reports_v = relations(
  _gallery_reports_v,
  ({ one, many }) => ({
    parent: one(gallery_reports, {
      fields: [_gallery_reports_v.parent],
      references: [gallery_reports.id],
      relationName: "parent",
    }),
    version_image: one(media, {
      fields: [_gallery_reports_v.version_image],
      references: [media.id],
      relationName: "version_image",
    }),
    version_photos: many(_gallery_reports_v_version_photos, {
      relationName: "version_photos",
    }),
  }),
);
export const relations_media = relations(media, () => ({}));
export const relations__media_v = relations(_media_v, ({ one }) => ({
  parent: one(media, {
    fields: [_media_v.parent],
    references: [media.id],
    relationName: "parent",
  }),
}));
export const relations_payload_kv = relations(payload_kv, () => ({}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
    eventsID: one(events, {
      fields: [payload_locked_documents_rels.eventsID],
      references: [events.id],
      relationName: "events",
    }),
    "menu-categoriesID": one(menu_categories, {
      fields: [payload_locked_documents_rels["menu-categoriesID"]],
      references: [menu_categories.id],
      relationName: "menu-categories",
    }),
    "gallery-videosID": one(gallery_videos, {
      fields: [payload_locked_documents_rels["gallery-videosID"]],
      references: [gallery_videos.id],
      relationName: "gallery-videos",
    }),
    "gallery-reportsID": one(gallery_reports, {
      fields: [payload_locked_documents_rels["gallery-reportsID"]],
      references: [gallery_reports.id],
      relationName: "gallery-reports",
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({}),
);
export const relations_settings = relations(settings, () => ({}));
export const relations_home_content_services = relations(
  home_content_services,
  ({ one }) => ({
    _parentID: one(home_content, {
      fields: [home_content_services._parentID],
      references: [home_content.id],
      relationName: "services",
    }),
  }),
);
export const relations_home_content_quick_nav = relations(
  home_content_quick_nav,
  ({ one }) => ({
    _parentID: one(home_content, {
      fields: [home_content_quick_nav._parentID],
      references: [home_content.id],
      relationName: "quickNav",
    }),
  }),
);
export const relations_home_content_rels = relations(
  home_content_rels,
  ({ one }) => ({
    parent: one(home_content, {
      fields: [home_content_rels.parent],
      references: [home_content.id],
      relationName: "_rels",
    }),
    "gallery-reportsID": one(gallery_reports, {
      fields: [home_content_rels["gallery-reportsID"]],
      references: [gallery_reports.id],
      relationName: "gallery-reports",
    }),
    "gallery-videosID": one(gallery_videos, {
      fields: [home_content_rels["gallery-videosID"]],
      references: [gallery_videos.id],
      relationName: "gallery-videos",
    }),
  }),
);
export const relations_home_content = relations(home_content, ({ many }) => ({
  services: many(home_content_services, {
    relationName: "services",
  }),
  quickNav: many(home_content_quick_nav, {
    relationName: "quickNav",
  }),
  _rels: many(home_content_rels, {
    relationName: "_rels",
  }),
}));

type DatabaseSchema = {
  enum_events_category: typeof enum_events_category;
  enum_events_day_of_week: typeof enum_events_day_of_week;
  enum_events_schedule_type: typeof enum_events_schedule_type;
  enum_events_admission: typeof enum_events_admission;
  enum_events_status: typeof enum_events_status;
  enum__events_v_version_category: typeof enum__events_v_version_category;
  enum__events_v_version_day_of_week: typeof enum__events_v_version_day_of_week;
  enum__events_v_version_schedule_type: typeof enum__events_v_version_schedule_type;
  enum__events_v_version_admission: typeof enum__events_v_version_admission;
  enum__events_v_version_status: typeof enum__events_v_version_status;
  enum_menu_categories_sections_dishes_badges_text: typeof enum_menu_categories_sections_dishes_badges_text;
  enum_menu_categories_group: typeof enum_menu_categories_group;
  enum_menu_categories_status: typeof enum_menu_categories_status;
  enum__menu_categories_v_version_sections_dishes_badges_text: typeof enum__menu_categories_v_version_sections_dishes_badges_text;
  enum__menu_categories_v_version_group: typeof enum__menu_categories_v_version_group;
  enum__menu_categories_v_version_status: typeof enum__menu_categories_v_version_status;
  enum_gallery_videos_status: typeof enum_gallery_videos_status;
  enum__gallery_videos_v_version_status: typeof enum__gallery_videos_v_version_status;
  enum_gallery_reports_category: typeof enum_gallery_reports_category;
  enum_gallery_reports_admission: typeof enum_gallery_reports_admission;
  enum_gallery_reports_status: typeof enum_gallery_reports_status;
  enum__gallery_reports_v_version_category: typeof enum__gallery_reports_v_version_category;
  enum__gallery_reports_v_version_admission: typeof enum__gallery_reports_v_version_admission;
  enum__gallery_reports_v_version_status: typeof enum__gallery_reports_v_version_status;
  users_sessions: typeof users_sessions;
  users: typeof users;
  events_hero_lines: typeof events_hero_lines;
  events_features: typeof events_features;
  events: typeof events;
  _events_v_version_hero_lines: typeof _events_v_version_hero_lines;
  _events_v_version_features: typeof _events_v_version_features;
  _events_v: typeof _events_v;
  menu_categories_sections_dishes_badges: typeof menu_categories_sections_dishes_badges;
  menu_categories_sections_dishes: typeof menu_categories_sections_dishes;
  menu_categories_sections: typeof menu_categories_sections;
  menu_categories: typeof menu_categories;
  _menu_categories_v_version_sections_dishes_badges: typeof _menu_categories_v_version_sections_dishes_badges;
  _menu_categories_v_version_sections_dishes: typeof _menu_categories_v_version_sections_dishes;
  _menu_categories_v_version_sections: typeof _menu_categories_v_version_sections;
  _menu_categories_v: typeof _menu_categories_v;
  gallery_videos_videos: typeof gallery_videos_videos;
  gallery_videos: typeof gallery_videos;
  _gallery_videos_v_version_videos: typeof _gallery_videos_v_version_videos;
  _gallery_videos_v: typeof _gallery_videos_v;
  gallery_reports_photos: typeof gallery_reports_photos;
  gallery_reports: typeof gallery_reports;
  _gallery_reports_v_version_photos: typeof _gallery_reports_v_version_photos;
  _gallery_reports_v: typeof _gallery_reports_v;
  media: typeof media;
  _media_v: typeof _media_v;
  payload_kv: typeof payload_kv;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  settings: typeof settings;
  home_content_services: typeof home_content_services;
  home_content_quick_nav: typeof home_content_quick_nav;
  home_content: typeof home_content;
  home_content_rels: typeof home_content_rels;
  relations_users_sessions: typeof relations_users_sessions;
  relations_users: typeof relations_users;
  relations_events_hero_lines: typeof relations_events_hero_lines;
  relations_events_features: typeof relations_events_features;
  relations_events: typeof relations_events;
  relations__events_v_version_hero_lines: typeof relations__events_v_version_hero_lines;
  relations__events_v_version_features: typeof relations__events_v_version_features;
  relations__events_v: typeof relations__events_v;
  relations_menu_categories_sections_dishes_badges: typeof relations_menu_categories_sections_dishes_badges;
  relations_menu_categories_sections_dishes: typeof relations_menu_categories_sections_dishes;
  relations_menu_categories_sections: typeof relations_menu_categories_sections;
  relations_menu_categories: typeof relations_menu_categories;
  relations__menu_categories_v_version_sections_dishes_badges: typeof relations__menu_categories_v_version_sections_dishes_badges;
  relations__menu_categories_v_version_sections_dishes: typeof relations__menu_categories_v_version_sections_dishes;
  relations__menu_categories_v_version_sections: typeof relations__menu_categories_v_version_sections;
  relations__menu_categories_v: typeof relations__menu_categories_v;
  relations_gallery_videos_videos: typeof relations_gallery_videos_videos;
  relations_gallery_videos: typeof relations_gallery_videos;
  relations__gallery_videos_v_version_videos: typeof relations__gallery_videos_v_version_videos;
  relations__gallery_videos_v: typeof relations__gallery_videos_v;
  relations_gallery_reports_photos: typeof relations_gallery_reports_photos;
  relations_gallery_reports: typeof relations_gallery_reports;
  relations__gallery_reports_v_version_photos: typeof relations__gallery_reports_v_version_photos;
  relations__gallery_reports_v: typeof relations__gallery_reports_v;
  relations_media: typeof relations_media;
  relations__media_v: typeof relations__media_v;
  relations_payload_kv: typeof relations_payload_kv;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
  relations_settings: typeof relations_settings;
  relations_home_content_services: typeof relations_home_content_services;
  relations_home_content_quick_nav: typeof relations_home_content_quick_nav;
  relations_home_content_rels: typeof relations_home_content_rels;
  relations_home_content: typeof relations_home_content;
};

declare module "@payloadcms/db-postgres" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
